Backport PloneFormGen migration to 1.x
collective/collective.easyform pull request #278
Opened 2021-06-11 09:44 UTC by thomasmassmann

Uses the existing migration and adjusts some imports and method calls to be compatible with 1.x.

It also sets the correct description for fieldsets (needs to be an attribute, not a property).

2021-06-11 10:03 UTC, thomasmassmann commented on .travis.yml
> +  # - "sh -e /etc/init.d/xvfb start"
Deactivated since only unit tests are run and travis-ci shuts down in 4 days.

2021-06-21 10:23 UTC, mauritsvanrees requested changes
I have two inline comments that should be addressed, about compatibility when `plone.app.contenttypes` is not available, and about linkintegrity.

Other than that, looks good. I tried it with fixes for those two points, and it worked on a site with three PloneFormGen forms.

Well, for one of them I got a lot of warnings: "Number of columns does not match. Skipping row 0 in data adapter". But that is probably already a problem in the old form, because it worked fine for one of the other two forms.

And for another, I got an error when filling in the resulting easyform: `NameError: global name 'ploneformgen' is not defined`. This is in a custom script adapter which excpects that `ploneformgen` is available as variable pointing to the form, but it should now be `easyform`. It would be nice if the migration would catch this. But this PR is a back port from master, and this one would likely fail on master as well. So: fine to ignore this detail.

Summary: please address my two inline comments. After that, it can be merged and I could do a release.

2021-06-21 10:23 UTC, mauritsvanrees commented on collective/easyform/migration/pfg.py
> +        migrate(portal, PloneFormGenMigrator)
I got a `LinkIntegrityNotificationException` here. So the code should switch off linkintegrity checks first.
This works for me:

```
        portal = getSite()

        # Switch linkintegrity off temporarily.
        ptool = getToolByName(self.context, "portal_properties")
        site_props = getattr(ptool, 'site_properties', None)
        link_integrity = False
        if site_props and site_props.hasProperty(
                'enable_link_integrity_checks'):
            link_integrity = site_props.getProperty(
                'enable_link_integrity_checks', False)
            if link_integrity:
                site_props.manage_changeProperties(
                    enable_link_integrity_checks=False)

        migrate(portal, PloneFormGenMigrator)

        # switch linkintegrity back on, if needed
        if link_integrity:
            site_props.manage_changeProperties(
                enable_link_integrity_checks=True
            )
```

2021-06-21 10:43 UTC, mauritsvanrees commented
FWIW, I quickly created a new PFG form with a fieldset. This looked ugly in PFG itself, but never mind that. After migration, it showed up as a proper fieldset in a new tab. So this new part of the migration seems fine. I cannot test how it would have gone without that part of the fix though.

2021-07-07 22:10 UTC, mauritsvanrees commented
@thomasmassmann Is this still on your radar?

2021-07-08 03:31 UTC, thomasmassmann commented
> @thomasmassmann Is this still on your radar?

@mauritsvanrees yes, i will add your changes and test it again with my initial setup.

2021-11-24 08:29 UTC, merged