Modify the 'Form Fields' to work with latest schemaeditor
collective/collective.easyform pull request #365
Opened 2022-07-27 18:19 UTC by frapell

fixes gh-345

This PR requires that https://github.com/plone/plone.schemaeditor/pull/92 and https://github.com/plone/mockup/pull/1203 are merged

2022-08-04 12:43 UTC, petschki requested changes

2022-08-04 12:43 UTC, petschki commented on src/collective/easyform/browser/fields_listing.pt
> +          <a id="delete-fieldset-${fieldset_name}" tal:condition="not:repeat/group/start"
Since these changes are for Plone 6 only I'd recommend to implement the `btn btn-sm btn-danger` classes here too like in `plone.schemaeditor`

2022-08-04 13:31 UTC, petschki approved these changes
LGTM. Unfortunately the PRs in `plone.schemaeditor` and `plone.staticresources` doesn't get green on Jenkins. The failures feel unrelated but I can reproduce them locally. Very strange. Need to check this first before merging this.

2022-08-04 13:48 UTC, frapell commented
@petschki Yup, also trying to figure out why the tests are failing...

2022-08-04 14:50 UTC, petschki commented
@frapell quick question: when I try to add a new Action I get the  following traceback:
```
2022-08-04 16:48:56,625 ERROR   [Zope.SiteErrorLog:35][waitress-0] AttributeError: http://localhost:8080/Plone2/new-form/@@actions/@@add-action
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 167, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 376, in publish_module
  Module ZPublisher.WSGIPublisher, line 271, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module plone.z3cform.layout, line 63, in __call__
  Module plone.z3cform.layout, line 47, in update
  Module plone.z3cform.fieldsets.extensible, line 65, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 132, in update
  Module plone.schemaeditor.browser.schema.add_field, line 102, in updateWidgets
AttributeError: 'NoneType' object has no attribute 'value'
```

does this have something to do with the latest `plone.schemaeditor` changes? `fieldset_id_widget` in this case is None ...

2022-08-04 14:53 UTC, petschki commented
note: I have checked out this PR and the schemaeditor PR https://github.com/plone/plone.schemaeditor/pull/92 together

2022-08-04 15:04 UTC, frapell commented
@petschki Yup, it is now fixed in `plone.schemaeditor`. Thanks!

2022-08-12 20:55 UTC, frapell commented
plone.schemaeditor and plone.staticresources PRs were merged, since this is approved I'll merge

2022-08-12 20:56 UTC, merged